# wrangler.toml
name = "gemini-proxy-panel"
main = "src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "e7bad1e74a114a66b325cbcabb1a31c4"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "e7bad1e74a114a66b325cbcabb1a31c4"

